[package]
name = "input"
version = "0.1.0"
edition = "2024"

[dependencies]
rppal = "0.18.0"
evdev = "0.12.2"
anyhow = "1.0.86"
log = "0.4.21"
env_logger = "0.11.3"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"